// AUTO-GENERATED by scripts/generate-hash-types.js
// Do not edit manually — run `node scripts/generate-hash-types.js` to regenerate.
// Source: example_hashes.md (main table lines 3–579 + specific hash types lines 633–668)
// Legacy hash types (lines 674+) are intentionally excluded.

export interface HashType {
  /** hashcat mode number as a string, e.g. "0", "1000" */
  mode: string;
  /** Human-readable name */
  name: string;
  /** Category for grouping in the UI */
  category: string;
}

export const HASH_TYPE_CATEGORIES: string[] = [
  "MD5",
  "SHA-1",
  "SHA-2",
  "SHA-3 / Keccak",
  "BLAKE2",
  "HMAC",
  "PBKDF2",
  "bcrypt / Unix Crypt",
  "Windows / AD",
  "Kerberos",
  "macOS",
  "Database",
  "Web Applications",
  "Network / WiFi",
  "Documents / Archives",
  "Full-Disk Encryption",
  "Cryptocurrency",
  "Password Managers",
  "Network Protocols",
  "Other"
];

export const HASH_TYPES: HashType[] = [
  {
    "mode": "0",
    "name": "MD5",
    "category": "MD5"
  },
  {
    "mode": "10",
    "name": "md5($pass.$salt)",
    "category": "MD5"
  },
  {
    "mode": "20",
    "name": "md5($salt.$pass)",
    "category": "MD5"
  },
  {
    "mode": "30",
    "name": "md5(utf16le($pass).$salt)",
    "category": "MD5"
  },
  {
    "mode": "40",
    "name": "md5($salt.utf16le($pass))",
    "category": "MD5"
  },
  {
    "mode": "50",
    "name": "HMAC-MD5 (key = $pass)",
    "category": "MD5"
  },
  {
    "mode": "60",
    "name": "HMAC-MD5 (key = $salt)",
    "category": "MD5"
  },
  {
    "mode": "70",
    "name": "md5(utf16le($pass))",
    "category": "MD5"
  },
  {
    "mode": "400",
    "name": "phpass, WordPress (MD5),   Joomla (MD5)",
    "category": "MD5"
  },
  {
    "mode": "500",
    "name": "md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5) 2",
    "category": "MD5"
  },
  {
    "mode": "1600",
    "name": "Apache $apr1$ MD5, md5apr1, MD5 (APR) 2",
    "category": "MD5"
  },
  {
    "mode": "2400",
    "name": "Cisco-PIX MD5",
    "category": "MD5"
  },
  {
    "mode": "2410",
    "name": "Cisco-ASA MD5",
    "category": "MD5"
  },
  {
    "mode": "2600",
    "name": "md5(md5($pass))",
    "category": "MD5"
  },
  {
    "mode": "2630",
    "name": "md5(md5($pass.$salt)) *",
    "category": "MD5"
  },
  {
    "mode": "3500",
    "name": "md5(md5(md5($pass)))",
    "category": "MD5"
  },
  {
    "mode": "3610",
    "name": "md5(md5(md5($pass)).$salt) *",
    "category": "MD5"
  },
  {
    "mode": "3710",
    "name": "md5($salt.md5($pass))",
    "category": "MD5"
  },
  {
    "mode": "3730",
    "name": "Dahua NVR/DVR/HVR (md5($salt1.strtoupper(md5($salt2.$pass)))) *",
    "category": "MD5"
  },
  {
    "mode": "3800",
    "name": "md5($salt.$pass.$salt)",
    "category": "MD5"
  },
  {
    "mode": "3910",
    "name": "md5(md5($pass).md5($salt))",
    "category": "MD5"
  },
  {
    "mode": "4010",
    "name": "md5($salt.md5($salt.$pass))",
    "category": "MD5"
  },
  {
    "mode": "4110",
    "name": "md5($salt.md5($pass.$salt))",
    "category": "MD5"
  },
  {
    "mode": "4300",
    "name": "md5(strtoupper(md5($pass)))",
    "category": "MD5"
  },
  {
    "mode": "4400",
    "name": "md5(sha1($pass))",
    "category": "MD5"
  },
  {
    "mode": "4410",
    "name": "md5(sha1($pass).$salt)",
    "category": "MD5"
  },
  {
    "mode": "4420",
    "name": "md5(sha1($pass.$salt)) *",
    "category": "MD5"
  },
  {
    "mode": "4430",
    "name": "md5(sha1($salt.$pass)) *",
    "category": "MD5"
  },
  {
    "mode": "4700",
    "name": "sha1(md5($pass))",
    "category": "MD5"
  },
  {
    "mode": "4710",
    "name": "sha1(md5($pass).$salt)",
    "category": "MD5"
  },
  {
    "mode": "4711",
    "name": "Huawei sha1(md5($pass).$salt)",
    "category": "MD5"
  },
  {
    "mode": "4800",
    "name": "iSCSI CHAP authentication, MD5(CHAP) 7",
    "category": "MD5"
  },
  {
    "mode": "5100",
    "name": "Half MD5",
    "category": "MD5"
  },
  {
    "mode": "5300",
    "name": "IKE-PSK MD5",
    "category": "MD5"
  },
  {
    "mode": "7350",
    "name": "IPMI2 RAKP HMAC-MD5 *",
    "category": "MD5"
  },
  {
    "mode": "9700",
    "name": "MS Office ⇐ 2003 MD5 + RC4, oldoffice$0, oldoffice$1",
    "category": "MD5"
  },
  {
    "mode": "9710",
    "name": "MS Office ⇐ 2003 $0/$1, MD5 + RC4, collider #1 23",
    "category": "MD5"
  },
  {
    "mode": "9720",
    "name": "MS Office ⇐ 2003 $0/$1, MD5 + RC4, collider #2",
    "category": "MD5"
  },
  {
    "mode": "10200",
    "name": "CRAM-MD5",
    "category": "MD5"
  },
  {
    "mode": "11100",
    "name": "PostgreSQL CRAM (MD5)",
    "category": "MD5"
  },
  {
    "mode": "11400",
    "name": "SIP digest authentication (MD5)",
    "category": "MD5"
  },
  {
    "mode": "11900",
    "name": "PBKDF2-HMAC-MD5",
    "category": "MD5"
  },
  {
    "mode": "16400",
    "name": "CRAM-MD5 Dovecot",
    "category": "MD5"
  },
  {
    "mode": "18500",
    "name": "sha1(md5(md5($pass)))",
    "category": "MD5"
  },
  {
    "mode": "19000",
    "name": "QNX /etc/shadow (MD5)",
    "category": "MD5"
  },
  {
    "mode": "20800",
    "name": "sha256(md5($pass))",
    "category": "MD5"
  },
  {
    "mode": "20900",
    "name": "md5(sha1($pass).md5($pass).sha1($pass))",
    "category": "MD5"
  },
  {
    "mode": "21100",
    "name": "sha1(md5($pass.$salt))",
    "category": "MD5"
  },
  {
    "mode": "21200",
    "name": "md5(sha1($salt).md5($pass))",
    "category": "MD5"
  },
  {
    "mode": "21300",
    "name": "md5($salt.sha1($salt.$pass))",
    "category": "MD5"
  },
  {
    "mode": "21310",
    "name": "md5($salt1.sha1($salt2.$pass)) *",
    "category": "MD5"
  },
  {
    "mode": "21900",
    "name": "md5(md5(md5($pass.$salt1)).$salt2)",
    "category": "MD5"
  },
  {
    "mode": "22500",
    "name": "MultiBit Classic.key (MD5)",
    "category": "MD5"
  },
  {
    "mode": "22800",
    "name": "Simpla CMS - md5($salt.$pass.md5($pass))",
    "category": "MD5"
  },
  {
    "mode": "24900",
    "name": "Dahua Authentication MD5",
    "category": "MD5"
  },
  {
    "mode": "24901",
    "name": "Besder Authentication MD5",
    "category": "MD5"
  },
  {
    "mode": "25000",
    "name": "SNMPv3 HMAC-MD5-96/HMAC-SHA1-96 8",
    "category": "MD5"
  },
  {
    "mode": "25100",
    "name": "SNMPv3 HMAC-MD5-96 8",
    "category": "MD5"
  },
  {
    "mode": "25600",
    "name": "bcrypt(md5($pass)) / bcryptmd5",
    "category": "MD5"
  },
  {
    "mode": "29930",
    "name": "ENCsecurity Datavault (MD5/no keychain) *",
    "category": "MD5"
  },
  {
    "mode": "29940",
    "name": "ENCsecurity Datavault (MD5/keychain) *",
    "category": "MD5"
  },
  {
    "mode": "30000",
    "name": "Python Werkzeug MD5 (HMAC-MD5 (key = $salt)) *",
    "category": "MD5"
  },
  {
    "mode": "30500",
    "name": "md5(md5($salt).md5(md5($pass))) *",
    "category": "MD5"
  },
  {
    "mode": "31700",
    "name": "md5(md5(md5($pass).$salt1).$salt2)",
    "category": "MD5"
  },
  {
    "mode": "32000",
    "name": "NetIQ SSPR (MD5)",
    "category": "MD5"
  },
  {
    "mode": "32800",
    "name": "md5(sha1(md5($pass)))",
    "category": "MD5"
  },
  {
    "mode": "33100",
    "name": "md5($salt.md5($pass).$salt)",
    "category": "MD5"
  },
  {
    "mode": "100",
    "name": "SHA1",
    "category": "SHA-1"
  },
  {
    "mode": "101",
    "name": "nsldap, SHA-1(Base64), Netscape LDAP SHA",
    "category": "SHA-1"
  },
  {
    "mode": "110",
    "name": "sha1($pass.$salt)",
    "category": "SHA-1"
  },
  {
    "mode": "120",
    "name": "sha1($salt.$pass)",
    "category": "SHA-1"
  },
  {
    "mode": "124",
    "name": "Django (SHA-1)",
    "category": "SHA-1"
  },
  {
    "mode": "130",
    "name": "sha1(utf16le($pass).$salt)",
    "category": "SHA-1"
  },
  {
    "mode": "140",
    "name": "sha1($salt.utf16le($pass))",
    "category": "SHA-1"
  },
  {
    "mode": "150",
    "name": "HMAC-SHA1 (key = $pass)",
    "category": "SHA-1"
  },
  {
    "mode": "160",
    "name": "HMAC-SHA1 (key = $salt)",
    "category": "SHA-1"
  },
  {
    "mode": "170",
    "name": "sha1(utf16le($pass))",
    "category": "SHA-1"
  },
  {
    "mode": "4500",
    "name": "sha1(sha1($pass))",
    "category": "SHA-1"
  },
  {
    "mode": "4510",
    "name": "sha1(sha1($pass).$salt)",
    "category": "SHA-1"
  },
  {
    "mode": "4520",
    "name": "sha1($salt.sha1($pass))",
    "category": "SHA-1"
  },
  {
    "mode": "4900",
    "name": "sha1($salt.$pass.$salt)",
    "category": "SHA-1"
  },
  {
    "mode": "5000",
    "name": "sha1(sha1($salt.$pass.$salt))",
    "category": "SHA-1"
  },
  {
    "mode": "5400",
    "name": "IKE-PSK SHA1",
    "category": "SHA-1"
  },
  {
    "mode": "7300",
    "name": "IPMI2 RAKP HMAC-SHA1",
    "category": "SHA-1"
  },
  {
    "mode": "8100",
    "name": "Citrix NetScaler (SHA1)",
    "category": "SHA-1"
  },
  {
    "mode": "9800",
    "name": "MS Office ⇐ 2003 SHA1 + RC4, oldoffice$3, oldoffice$4",
    "category": "SHA-1"
  },
  {
    "mode": "9810",
    "name": "MS Office ⇐ 2003 $3, SHA1 + RC4, collider #1 24",
    "category": "SHA-1"
  },
  {
    "mode": "9820",
    "name": "MS Office ⇐ 2003 $3, SHA1 + RC4, collider #2",
    "category": "SHA-1"
  },
  {
    "mode": "11200",
    "name": "MySQL CRAM (SHA1)",
    "category": "SHA-1"
  },
  {
    "mode": "12000",
    "name": "PBKDF2-HMAC-SHA1",
    "category": "SHA-1"
  },
  {
    "mode": "12001",
    "name": "Atlassian (PBKDF2-HMAC-SHA1)",
    "category": "SHA-1"
  },
  {
    "mode": "13300",
    "name": "AxCrypt 1 in-memory SHA1 13",
    "category": "SHA-1"
  },
  {
    "mode": "14400",
    "name": "sha1(CX)",
    "category": "SHA-1"
  },
  {
    "mode": "15500",
    "name": "JKS Java Key Store Private Keys (SHA1)",
    "category": "SHA-1"
  },
  {
    "mode": "17010",
    "name": "GPG (AES-128/AES-256 (SHA-1($pass))) *",
    "category": "SHA-1"
  },
  {
    "mode": "18100",
    "name": "TOTP (HMAC-SHA1)",
    "category": "SHA-1"
  },
  {
    "mode": "18600",
    "name": "Open Document Format (ODF) 1.1 (SHA-1, Blowfish)",
    "category": "SHA-1"
  },
  {
    "mode": "19300",
    "name": "sha1($salt1.$pass.$salt2)",
    "category": "SHA-1"
  },
  {
    "mode": "19600",
    "name": "Kerberos 5, etype 17, TGS-REP (AES128-CTS-HMAC-SHA1-96)",
    "category": "SHA-1"
  },
  {
    "mode": "19700",
    "name": "Kerberos 5, etype 18, TGS-REP (AES256-CTS-HMAC-SHA1-96)",
    "category": "SHA-1"
  },
  {
    "mode": "20400",
    "name": "Python passlib pbkdf2-sha1",
    "category": "SHA-1"
  },
  {
    "mode": "22600",
    "name": "Telegram Desktop < v2.1.14 (PBKDF2-HMAC-SHA1)",
    "category": "SHA-1"
  },
  {
    "mode": "23200",
    "name": "XMPP SCRAM PBKDF2-SHA1",
    "category": "SHA-1"
  },
  {
    "mode": "24100",
    "name": "MongoDB ServerKey SCRAM-SHA-1",
    "category": "SHA-1"
  },
  {
    "mode": "24300",
    "name": "sha1($salt.sha1($pass.$salt))",
    "category": "SHA-1"
  },
  {
    "mode": "24410",
    "name": "PKCS#8 Private Keys (PBKDF2-HMAC-SHA1 + 3DES/AES)",
    "category": "SHA-1"
  },
  {
    "mode": "24800",
    "name": "Umbraco HMAC-SHA1",
    "category": "SHA-1"
  },
  {
    "mode": "25200",
    "name": "SNMPv3 HMAC-SHA1-96 8",
    "category": "SHA-1"
  },
  {
    "mode": "25800",
    "name": "bcrypt(sha1($pass)) / bcryptsha1",
    "category": "SHA-1"
  },
  {
    "mode": "27400",
    "name": "VMware VMX (PBKDF2-HMAC-SHA1 + AES-256-CBC)",
    "category": "SHA-1"
  },
  {
    "mode": "29000",
    "name": "sha1($salt.sha1(utf16le($username).':'.utf16le($pass)))",
    "category": "SHA-1"
  },
  {
    "mode": "29511",
    "name": "LUKS v1 SHA-1 + AES",
    "category": "SHA-1"
  },
  {
    "mode": "29512",
    "name": "LUKS v1 SHA-1 + Serpent",
    "category": "SHA-1"
  },
  {
    "mode": "29513",
    "name": "LUKS v1 SHA-1 + Twofish",
    "category": "SHA-1"
  },
  {
    "mode": "32010",
    "name": "NetIQ SSPR (SHA1)",
    "category": "SHA-1"
  },
  {
    "mode": "32020",
    "name": "NetIQ SSPR (SHA-1 with Salt)",
    "category": "SHA-1"
  },
  {
    "mode": "32900",
    "name": "PBKDF1-SHA1",
    "category": "SHA-1"
  },
  {
    "mode": "34500",
    "name": "sha224(sha1($pass))",
    "category": "SHA-1"
  },
  {
    "mode": "1300",
    "name": "SHA2-224",
    "category": "SHA-2"
  },
  {
    "mode": "1310",
    "name": "sha224($pass.$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "1320",
    "name": "sha224($salt.$pass)",
    "category": "SHA-2"
  },
  {
    "mode": "1400",
    "name": "SHA2-256",
    "category": "SHA-2"
  },
  {
    "mode": "1410",
    "name": "sha256($pass.$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "1420",
    "name": "sha256($salt.$pass)",
    "category": "SHA-2"
  },
  {
    "mode": "1430",
    "name": "sha256(utf16le($pass).$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "1440",
    "name": "sha256($salt.utf16le($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "1450",
    "name": "HMAC-SHA256 (key = $pass)",
    "category": "SHA-2"
  },
  {
    "mode": "1460",
    "name": "HMAC-SHA256 (key = $salt)",
    "category": "SHA-2"
  },
  {
    "mode": "1470",
    "name": "sha256(utf16le($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "1700",
    "name": "SHA2-512",
    "category": "SHA-2"
  },
  {
    "mode": "1710",
    "name": "sha512($pass.$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "1720",
    "name": "sha512($salt.$pass)",
    "category": "SHA-2"
  },
  {
    "mode": "1730",
    "name": "sha512(utf16le($pass).$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "1740",
    "name": "sha512($salt.utf16le($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "1750",
    "name": "HMAC-SHA512 (key = $pass)",
    "category": "SHA-2"
  },
  {
    "mode": "1760",
    "name": "HMAC-SHA512 (key = $salt)",
    "category": "SHA-2"
  },
  {
    "mode": "1770",
    "name": "sha512(utf16le($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "1800",
    "name": "sha512crypt $6$, SHA512 (Unix) 2",
    "category": "SHA-2"
  },
  {
    "mode": "5700",
    "name": "Cisco-IOS type 4 (SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "5720",
    "name": "Cisco-ISE Hashed Password (SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "6221",
    "name": "TrueCrypt 5.0+ SHA512 + AES (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "6222",
    "name": "TrueCrypt 5.0+ SHA512 + AES-Twofish (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "6223",
    "name": "TrueCrypt 5.0+ SHA512 + AES-Twofish-Serpent (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "7100",
    "name": "macOS v10.8+ (PBKDF2-SHA512)",
    "category": "SHA-2"
  },
  {
    "mode": "7400",
    "name": "sha256crypt $5$, SHA256 (Unix) 2",
    "category": "SHA-2"
  },
  {
    "mode": "9200",
    "name": "Cisco-IOS $8$ (PBKDF2-SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "10000",
    "name": "Django (PBKDF2-SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "10800",
    "name": "SHA2-384",
    "category": "SHA-2"
  },
  {
    "mode": "10810",
    "name": "sha384($pass.$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "10820",
    "name": "sha384($salt.$pass)",
    "category": "SHA-2"
  },
  {
    "mode": "10830",
    "name": "sha384(utf16le($pass).$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "10840",
    "name": "sha384($salt.utf16le($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "10870",
    "name": "sha384(utf16le($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "10900",
    "name": "PBKDF2-HMAC-SHA256",
    "category": "SHA-2"
  },
  {
    "mode": "10901",
    "name": "RedHat 389-DS LDAP (PBKDF2-HMAC-SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "12100",
    "name": "PBKDF2-HMAC-SHA512",
    "category": "SHA-2"
  },
  {
    "mode": "12150",
    "name": "Apache Shiro 1 SHA-512",
    "category": "SHA-2"
  },
  {
    "mode": "12800",
    "name": "MS-AzureSync PBKDF2-HMAC-SHA256",
    "category": "SHA-2"
  },
  {
    "mode": "13721",
    "name": "VeraCrypt PBKDF2-HMAC-SHA512 + AES (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "13722",
    "name": "VeraCrypt PBKDF2-HMAC-SHA512 + AES-Twofish (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "13723",
    "name": "VeraCrypt PBKDF2-HMAC-SHA512 + Serpent-Twofish-AES (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "13751",
    "name": "VeraCrypt PBKDF2-HMAC-SHA256 + AES (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "13752",
    "name": "VeraCrypt PBKDF2-HMAC-SHA256 + AES-Twofish (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "13753",
    "name": "VeraCrypt PBKDF2-HMAC-SHA256 + Serpent-Twofish-AES (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "13761",
    "name": "VeraCrypt PBKDF2-HMAC-SHA256 + boot-mode + Twofish (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "13762",
    "name": "VeraCrypt PBKDF2-HMAC-SHA256 + boot-mode + Serpent-AES (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "13763",
    "name": "VeraCrypt PBKDF2-HMAC-SHA256 + boot-mode + Serpent-Twofish-AES (legacy)",
    "category": "SHA-2"
  },
  {
    "mode": "15600",
    "name": "Ethereum Wallet, PBKDF2-HMAC-SHA256",
    "category": "SHA-2"
  },
  {
    "mode": "16300",
    "name": "Ethereum Pre-Sale Wallet, PBKDF2-HMAC-SHA256",
    "category": "SHA-2"
  },
  {
    "mode": "17020",
    "name": "GPG (AES-128/AES-256 (SHA-512($pass))) *",
    "category": "SHA-2"
  },
  {
    "mode": "17030",
    "name": "GPG (AES-128/AES-256 (SHA-256($pass))) *",
    "category": "SHA-2"
  },
  {
    "mode": "18400",
    "name": "Open Document Format (ODF) 1.2 (SHA-256, AES)",
    "category": "SHA-2"
  },
  {
    "mode": "18800",
    "name": "Blockchain, My Wallet, Second Password (SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "19100",
    "name": "QNX /etc/shadow (SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "19200",
    "name": "QNX /etc/shadow (SHA512)",
    "category": "SHA-2"
  },
  {
    "mode": "19210",
    "name": "QNX 7 /etc/shadow (SHA512)",
    "category": "SHA-2"
  },
  {
    "mode": "20011",
    "name": "DiskCryptor SHA512 + XTS 512 bit (AES)",
    "category": "SHA-2"
  },
  {
    "mode": "20012",
    "name": "DiskCryptor SHA512 + XTS 1024 bit (AES-Twofish)",
    "category": "SHA-2"
  },
  {
    "mode": "20013",
    "name": "DiskCryptor SHA512 + XTS 1536 bit (AES-Twofish-Serpent)",
    "category": "SHA-2"
  },
  {
    "mode": "20200",
    "name": "Python passlib pbkdf2-sha512",
    "category": "SHA-2"
  },
  {
    "mode": "20300",
    "name": "Python passlib pbkdf2-sha256",
    "category": "SHA-2"
  },
  {
    "mode": "20600",
    "name": "Oracle Transportation Management (SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "20710",
    "name": "sha256(sha256($pass).$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "20711",
    "name": "AuthMe sha256",
    "category": "SHA-2"
  },
  {
    "mode": "20712",
    "name": "RSA Security Analytics / NetWitness (sha256) *",
    "category": "SHA-2"
  },
  {
    "mode": "20720",
    "name": "sha256($salt.sha256($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "20730",
    "name": "sha256(sha256($pass.$salt))",
    "category": "SHA-2"
  },
  {
    "mode": "21000",
    "name": "BitShares v0.x - sha512(sha512\\_bin(pass))",
    "category": "SHA-2"
  },
  {
    "mode": "21400",
    "name": "sha256(sha256\\_bin($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "21420",
    "name": "sha256($salt.sha256\\_bin($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "21600",
    "name": "Web2py pbkdf2-sha512",
    "category": "SHA-2"
  },
  {
    "mode": "22200",
    "name": "Citrix NetScaler (SHA512)",
    "category": "SHA-2"
  },
  {
    "mode": "22300",
    "name": "sha256($salt.$pass.$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "22301",
    "name": "Telegram Mobile App Passcode (SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "22400",
    "name": "AES Crypt (SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "24200",
    "name": "MongoDB ServerKey SCRAM-SHA-256",
    "category": "SHA-2"
  },
  {
    "mode": "24420",
    "name": "PKCS#8 Private Keys (PBKDF2-HMAC-SHA256 + 3DES/AES)",
    "category": "SHA-2"
  },
  {
    "mode": "24500",
    "name": "Telegram Desktop >= v2.1.14 (PBKDF2-HMAC-SHA512)",
    "category": "SHA-2"
  },
  {
    "mode": "26700",
    "name": "SNMPv3 HMAC-SHA224-128 8",
    "category": "SHA-2"
  },
  {
    "mode": "26800",
    "name": "SNMPv3 HMAC-SHA256-192 8 8",
    "category": "SHA-2"
  },
  {
    "mode": "26900",
    "name": "SNMPv3 HMAC-SHA384-256 8",
    "category": "SHA-2"
  },
  {
    "mode": "27300",
    "name": "SNMPv3 HMAC-SHA512-384 8",
    "category": "SHA-2"
  },
  {
    "mode": "27500",
    "name": "VirtualBox (PBKDF2-HMAC-SHA256 & AES-128-XTS)",
    "category": "SHA-2"
  },
  {
    "mode": "27600",
    "name": "VirtualBox (PBKDF2-HMAC-SHA256 & AES-256-XTS)",
    "category": "SHA-2"
  },
  {
    "mode": "28400",
    "name": "bcrypt(sha512($pass)) / bcryptsha512",
    "category": "SHA-2"
  },
  {
    "mode": "28600",
    "name": "PostgreSQL SCRAM-SHA-256",
    "category": "SHA-2"
  },
  {
    "mode": "28700",
    "name": "Amazon AWS4-HMAC-SHA256",
    "category": "SHA-2"
  },
  {
    "mode": "29321",
    "name": "TrueCrypt SHA512 + XTS 512 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29322",
    "name": "TrueCrypt SHA512 + XTS 1024 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29323",
    "name": "TrueCrypt SHA512 + XTS 1536 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29421",
    "name": "VeraCrypt SHA512 + XTS 512 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29422",
    "name": "VeraCrypt SHA512 + XTS 1024 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29423",
    "name": "VeraCrypt SHA512 + XTS 1536 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29451",
    "name": "VeraCrypt SHA256 + XTS 512 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29452",
    "name": "VeraCrypt SHA256 + XTS 1024 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29453",
    "name": "VeraCrypt SHA256 + XTS 1536 bit",
    "category": "SHA-2"
  },
  {
    "mode": "29461",
    "name": "VeraCrypt SHA256 + XTS 512 bit + boot-mode",
    "category": "SHA-2"
  },
  {
    "mode": "29462",
    "name": "VeraCrypt SHA256 + XTS 1024 bit + boot-mode",
    "category": "SHA-2"
  },
  {
    "mode": "29463",
    "name": "VeraCrypt SHA256 + XTS 1536 bit + boot-mode",
    "category": "SHA-2"
  },
  {
    "mode": "29521",
    "name": "LUKS v1 SHA-256 + AES",
    "category": "SHA-2"
  },
  {
    "mode": "29522",
    "name": "LUKS v1 SHA-256 + Serpent",
    "category": "SHA-2"
  },
  {
    "mode": "29523",
    "name": "LUKS v1 SHA-256 + Twofish",
    "category": "SHA-2"
  },
  {
    "mode": "29531",
    "name": "LUKS v1 SHA-512 + AES",
    "category": "SHA-2"
  },
  {
    "mode": "29532",
    "name": "LUKS v1 SHA-512 + Serpent",
    "category": "SHA-2"
  },
  {
    "mode": "29533",
    "name": "LUKS v1 SHA-512 + Twofish",
    "category": "SHA-2"
  },
  {
    "mode": "30120",
    "name": "Python Werkzeug SHA256 (HMAC-SHA256 (key = $salt)) *",
    "category": "SHA-2"
  },
  {
    "mode": "30420",
    "name": "DANE RFC7929/RFC8162 SHA2-256 *",
    "category": "SHA-2"
  },
  {
    "mode": "30600",
    "name": "bcrypt(sha256($pass)) / bcryptsha256 *",
    "category": "SHA-2"
  },
  {
    "mode": "30601",
    "name": "bcrypt(HMAC-SHA256($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "32030",
    "name": "NetIQ SSPR (SHA-256 with Salt)",
    "category": "SHA-2"
  },
  {
    "mode": "32031",
    "name": "Adobe AEM (SSPR, SHA-256 with Salt)",
    "category": "SHA-2"
  },
  {
    "mode": "32040",
    "name": "NetIQ SSPR (SHA-512 with Salt)",
    "category": "SHA-2"
  },
  {
    "mode": "32041",
    "name": "Adobe AEM (SSPR, SHA-512 with Salt)",
    "category": "SHA-2"
  },
  {
    "mode": "32410",
    "name": "sha512(sha512($pass).$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "32420",
    "name": "sha512(sha512\\_bin($pass).$salt)",
    "category": "SHA-2"
  },
  {
    "mode": "33400",
    "name": "mega.nz password-protected link (PBKDF2-HMAC-SHA512)",
    "category": "SHA-2"
  },
  {
    "mode": "33700",
    "name": "Microsoft Online Account (PBKDF2-HMAC-SHA256 + AES256)",
    "category": "SHA-2"
  },
  {
    "mode": "33900",
    "name": "Citrix NetScaler (PBKDF2-HMAC-SHA256)",
    "category": "SHA-2"
  },
  {
    "mode": "34400",
    "name": "sha224(sha224($pass))",
    "category": "SHA-2"
  },
  {
    "mode": "17300",
    "name": "SHA3-224",
    "category": "SHA-3 / Keccak"
  },
  {
    "mode": "17400",
    "name": "SHA3-256",
    "category": "SHA-3 / Keccak"
  },
  {
    "mode": "17500",
    "name": "SHA3-384",
    "category": "SHA-3 / Keccak"
  },
  {
    "mode": "17600",
    "name": "SHA3-512",
    "category": "SHA-3 / Keccak"
  },
  {
    "mode": "17700",
    "name": "Keccak-224",
    "category": "SHA-3 / Keccak"
  },
  {
    "mode": "17800",
    "name": "Keccak-256",
    "category": "SHA-3 / Keccak"
  },
  {
    "mode": "17900",
    "name": "Keccak-384",
    "category": "SHA-3 / Keccak"
  },
  {
    "mode": "18000",
    "name": "Keccak-512",
    "category": "SHA-3 / Keccak"
  },
  {
    "mode": "600",
    "name": "BLAKE2b-512",
    "category": "BLAKE2"
  },
  {
    "mode": "610",
    "name": "BLAKE2b-512($pass.$salt)",
    "category": "BLAKE2"
  },
  {
    "mode": "620",
    "name": "BLAKE2b-512($salt.$pass)",
    "category": "BLAKE2"
  },
  {
    "mode": "31000",
    "name": "BLAKE2s-256 *",
    "category": "BLAKE2"
  },
  {
    "mode": "33300",
    "name": "HMAC-BLAKE2S (key = $pass)",
    "category": "BLAKE2"
  },
  {
    "mode": "34800",
    "name": "BLAKE2b-256",
    "category": "BLAKE2"
  },
  {
    "mode": "34810",
    "name": "BLAKE2b-256($pass.$salt)",
    "category": "BLAKE2"
  },
  {
    "mode": "34820",
    "name": "BLAKE2b-256($salt.$pass)",
    "category": "BLAKE2"
  },
  {
    "mode": "6050",
    "name": "HMAC-RIPEMD160 (key = $pass) *",
    "category": "HMAC"
  },
  {
    "mode": "6060",
    "name": "HMAC-RIPEMD160 (key = $salt) *",
    "category": "HMAC"
  },
  {
    "mode": "6211",
    "name": "TrueCrypt 5.0+ PBKDF2-HMAC-RIPEMD160 + AES (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "6212",
    "name": "TrueCrypt 5.0+ PBKDF2-HMAC-RIPEMD160 + AES-Twofish (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "6213",
    "name": "TrueCrypt 5.0+ PBKDF2-HMAC-RIPEMD160 + AES-Twofish-Serpent (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "6241",
    "name": "TrueCrypt 5.0+ PBKDF2-HMAC-RIPEMD160 + AES + boot (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "6242",
    "name": "TrueCrypt 5.0+ PBKDF2-HMAC-RIPEMD160 + AES-Twofish + boot (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "6243",
    "name": "TrueCrypt 5.0+ PBKDF2-HMAC-RIPEMD160 + AES-Twofish-Serpent + boot (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "11750",
    "name": "HMAC-Streebog-256 (key = $pass), big-endian",
    "category": "HMAC"
  },
  {
    "mode": "11760",
    "name": "HMAC-Streebog-256 (key = $salt), big-endian",
    "category": "HMAC"
  },
  {
    "mode": "11850",
    "name": "HMAC-Streebog-512 (key = $pass), big-endian",
    "category": "HMAC"
  },
  {
    "mode": "11860",
    "name": "HMAC-Streebog-512 (key = $salt), big-endian",
    "category": "HMAC"
  },
  {
    "mode": "13711",
    "name": "VeraCrypt PBKDF2-HMAC-RIPEMD160 + AES (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "13712",
    "name": "VeraCrypt PBKDF2-HMAC-RIPEMD160 + AES-Twofish (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "13713",
    "name": "VeraCrypt PBKDF2-HMAC-RIPEMD160 + Serpent-Twofish-AES (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "13731",
    "name": "VeraCrypt PBKDF2-HMAC-Whirlpool + AES (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "13732",
    "name": "VeraCrypt PBKDF2-HMAC-Whirlpool + AES-Twofish (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "13733",
    "name": "VeraCrypt PBKDF2-HMAC-Whirlpool + Serpent-Twofish-AES (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "13741",
    "name": "VeraCrypt PBKDF2-HMAC-RIPEMD160 + boot-mode + AES (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "13742",
    "name": "VeraCrypt PBKDF2-HMAC-RIPEMD160 + boot-mode + AES-Twofish (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "13743",
    "name": "VeraCrypt PBKDF2-HMAC-RIPEMD160 + boot-mode + AES-Twofish-Serpent (legacy)",
    "category": "HMAC"
  },
  {
    "mode": "33650",
    "name": "HMAC-RIPEMD320 (key = $pass)",
    "category": "HMAC"
  },
  {
    "mode": "33660",
    "name": "HMAC-RIPEMD320 (key = $salt)",
    "category": "HMAC"
  },
  {
    "mode": "2500",
    "name": "WPA-EAPOL-PBKDF2 1",
    "category": "PBKDF2"
  },
  {
    "mode": "16800",
    "name": "WPA-PMKID-PBKDF2 1",
    "category": "PBKDF2"
  },
  {
    "mode": "22000",
    "name": "WPA-PBKDF2-PMKID+EAPOL 1",
    "category": "PBKDF2"
  },
  {
    "mode": "29600",
    "name": "Terra Station Wallet (AES256-CBC(PBKDF2($pass)))",
    "category": "PBKDF2"
  },
  {
    "mode": "29910",
    "name": "ENCsecurity Datavault (PBKDF2/no keychain) *",
    "category": "PBKDF2"
  },
  {
    "mode": "29920",
    "name": "ENCsecurity Datavault (PBKDF2/keychain) *",
    "category": "PBKDF2"
  },
  {
    "mode": "32050",
    "name": "NetIQ SSPR (PBKDF2WithHmacSHA1)",
    "category": "PBKDF2"
  },
  {
    "mode": "32060",
    "name": "NetIQ SSPR (PBKDF2WithHmacSHA256)",
    "category": "PBKDF2"
  },
  {
    "mode": "32070",
    "name": "NetIQ SSPR (PBKDF2WithHmacSHA512)",
    "category": "PBKDF2"
  },
  {
    "mode": "1500",
    "name": "descrypt, DES (Unix), Traditional DES",
    "category": "bcrypt / Unix Crypt"
  },
  {
    "mode": "3200",
    "name": "bcrypt $2\\*$, Blowfish (Unix)",
    "category": "bcrypt / Unix Crypt"
  },
  {
    "mode": "7401",
    "name": "MySQL $A$ (sha256crypt) 19",
    "category": "bcrypt / Unix Crypt"
  },
  {
    "mode": "12400",
    "name": "BSDi Crypt, Extended DES",
    "category": "bcrypt / Unix Crypt"
  },
  {
    "mode": "33800",
    "name": "WBB4 (Woltlab Burning Board) \\[bcrypt(bcrypt($pass))\\]",
    "category": "bcrypt / Unix Crypt"
  },
  {
    "mode": "35100",
    "name": "sm3crypt $sm3$, SM3 (Unix)",
    "category": "bcrypt / Unix Crypt"
  },
  {
    "mode": "1000",
    "name": "NTLM",
    "category": "Windows / AD"
  },
  {
    "mode": "2100",
    "name": "Domain Cached Credentials 2 (DCC2), MS Cache 2",
    "category": "Windows / AD"
  },
  {
    "mode": "3000",
    "name": "LM",
    "category": "Windows / AD"
  },
  {
    "mode": "5500",
    "name": "NetNTLMv1 / NetNTLMv1+ESS",
    "category": "Windows / AD"
  },
  {
    "mode": "5600",
    "name": "NetNTLMv2",
    "category": "Windows / AD"
  },
  {
    "mode": "13800",
    "name": "Windows Phone 8+ PIN/password",
    "category": "Windows / AD"
  },
  {
    "mode": "15900",
    "name": "DPAPI masterkey file v2 + Active Directory domain context",
    "category": "Windows / AD"
  },
  {
    "mode": "27000",
    "name": "NetNTLMv1 / NetNTLMv1+ESS (NT) 22",
    "category": "Windows / AD"
  },
  {
    "mode": "27100",
    "name": "NetNTLMv2 (NT) 22",
    "category": "Windows / AD"
  },
  {
    "mode": "28100",
    "name": "Windows Hello PIN/Password",
    "category": "Windows / AD"
  },
  {
    "mode": "7500",
    "name": "Kerberos 5, etype 23, AS-REQ Pre-Auth",
    "category": "Kerberos"
  },
  {
    "mode": "13100",
    "name": "Kerberos 5, etype 23, TGS-REP",
    "category": "Kerberos"
  },
  {
    "mode": "18200",
    "name": "Kerberos 5, etype 23, AS-REP",
    "category": "Kerberos"
  },
  {
    "mode": "19800",
    "name": "Kerberos 5, etype 17, Pre-Auth",
    "category": "Kerberos"
  },
  {
    "mode": "19900",
    "name": "Kerberos 5, etype 18, Pre-Auth",
    "category": "Kerberos"
  },
  {
    "mode": "28800",
    "name": "Kerberos 5, etype 17, DB",
    "category": "Kerberos"
  },
  {
    "mode": "28900",
    "name": "Kerberos 5, etype 18, DB",
    "category": "Kerberos"
  },
  {
    "mode": "122",
    "name": "macOS v10.4, macOS v10.5, macOS v10.6",
    "category": "macOS"
  },
  {
    "mode": "1722",
    "name": "macOS v10.7",
    "category": "macOS"
  },
  {
    "mode": "16200",
    "name": "Apple Secure Notes",
    "category": "macOS"
  },
  {
    "mode": "18300",
    "name": "Apple File System (APFS)",
    "category": "macOS"
  },
  {
    "mode": "23100",
    "name": "Apple Keychain",
    "category": "macOS"
  },
  {
    "mode": "23300",
    "name": "Apple iWork",
    "category": "macOS"
  },
  {
    "mode": "12",
    "name": "PostgreSQL",
    "category": "Database"
  },
  {
    "mode": "112",
    "name": "Oracle S: Type (Oracle 11+)",
    "category": "Database"
  },
  {
    "mode": "131",
    "name": "MSSQL (2000)",
    "category": "Database"
  },
  {
    "mode": "132",
    "name": "MSSQL (2005)",
    "category": "Database"
  },
  {
    "mode": "200",
    "name": "MySQL323",
    "category": "Database"
  },
  {
    "mode": "300",
    "name": "MySQL4.1/MySQL5",
    "category": "Database"
  },
  {
    "mode": "1731",
    "name": "MSSQL (2012, 2014)",
    "category": "Database"
  },
  {
    "mode": "3100",
    "name": "Oracle H: Type (Oracle 7+)",
    "category": "Database"
  },
  {
    "mode": "8000",
    "name": "Sybase ASE",
    "category": "Database"
  },
  {
    "mode": "12300",
    "name": "Oracle T: Type (Oracle 12+)",
    "category": "Database"
  },
  {
    "mode": "11",
    "name": "Joomla < 2.5.18",
    "category": "Web Applications"
  },
  {
    "mode": "121",
    "name": "SMF (Simple Machines Forum) > v1.1",
    "category": "Web Applications"
  },
  {
    "mode": "2611",
    "name": "vBulletin < v3.8.5",
    "category": "Web Applications"
  },
  {
    "mode": "2711",
    "name": "vBulletin >= v3.8.5",
    "category": "Web Applications"
  },
  {
    "mode": "2811",
    "name": "MyBB 1.2+, IPB2+ (Invision Power Board)",
    "category": "Web Applications"
  },
  {
    "mode": "3711",
    "name": "MediaWiki B type",
    "category": "Web Applications"
  },
  {
    "mode": "4522",
    "name": "PunBB",
    "category": "Web Applications"
  },
  {
    "mode": "7900",
    "name": "Drupal7",
    "category": "Web Applications"
  },
  {
    "mode": "19500",
    "name": "Ruby on Rails Restful-Authentication",
    "category": "Web Applications"
  },
  {
    "mode": "27200",
    "name": "Ruby on Rails Restful Auth (one round, no sitekey)",
    "category": "Web Applications"
  },
  {
    "mode": "29100",
    "name": "Flask Session Cookie ($salt.$salt.$pass)",
    "category": "Web Applications"
  },
  {
    "mode": "2501",
    "name": "WPA-EAPOL-PMK 14",
    "category": "Network / WiFi"
  },
  {
    "mode": "16801",
    "name": "WPA-PMKID-PMK 15",
    "category": "Network / WiFi"
  },
  {
    "mode": "22001",
    "name": "WPA-PMK-PMKID+EAPOL 18",
    "category": "Network / WiFi"
  },
  {
    "mode": "5200",
    "name": "Password Safe v3",
    "category": "Documents / Archives"
  },
  {
    "mode": "5800",
    "name": "Samsung Android Password/PIN",
    "category": "Documents / Archives"
  },
  {
    "mode": "6600",
    "name": "1Password, agilekeychain",
    "category": "Documents / Archives"
  },
  {
    "mode": "8200",
    "name": "1Password, cloudkeychain",
    "category": "Documents / Archives"
  },
  {
    "mode": "9000",
    "name": "Password Safe v2",
    "category": "Documents / Archives"
  },
  {
    "mode": "9400",
    "name": "MS Office 2007",
    "category": "Documents / Archives"
  },
  {
    "mode": "9500",
    "name": "MS Office 2010",
    "category": "Documents / Archives"
  },
  {
    "mode": "9600",
    "name": "MS Office 2013",
    "category": "Documents / Archives"
  },
  {
    "mode": "10400",
    "name": "PDF 1.1 - 1.3 (Acrobat 2 - 4)",
    "category": "Documents / Archives"
  },
  {
    "mode": "10410",
    "name": "PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #1 25",
    "category": "Documents / Archives"
  },
  {
    "mode": "10420",
    "name": "PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #2",
    "category": "Documents / Archives"
  },
  {
    "mode": "10500",
    "name": "PDF 1.4 - 1.6 (Acrobat 5 - 8)",
    "category": "Documents / Archives"
  },
  {
    "mode": "10510",
    "name": "PDF 1.3 - 1.6 (Acrobat 4 - 8) w/ RC4-40",
    "category": "Documents / Archives"
  },
  {
    "mode": "10600",
    "name": "PDF 1.7 Level 3 (Acrobat 9)",
    "category": "Documents / Archives"
  },
  {
    "mode": "10700",
    "name": "PDF 1.7 Level 8 (Acrobat 10 - 11)",
    "category": "Documents / Archives"
  },
  {
    "mode": "11600",
    "name": "7-Zip",
    "category": "Documents / Archives"
  },
  {
    "mode": "13600",
    "name": "WinZip",
    "category": "Documents / Archives"
  },
  {
    "mode": "17200",
    "name": "PKZIP (Compressed)",
    "category": "Documents / Archives"
  },
  {
    "mode": "17210",
    "name": "PKZIP (Uncompressed)",
    "category": "Documents / Archives"
  },
  {
    "mode": "17220",
    "name": "PKZIP (Compressed Multi-File)",
    "category": "Documents / Archives"
  },
  {
    "mode": "17225",
    "name": "PKZIP (Mixed Multi-File)",
    "category": "Documents / Archives"
  },
  {
    "mode": "17230",
    "name": "PKZIP (Mixed Multi-File Checksum-Only)",
    "category": "Documents / Archives"
  },
  {
    "mode": "20500",
    "name": "PKZIP Master Key",
    "category": "Documents / Archives"
  },
  {
    "mode": "20510",
    "name": "PKZIP Master Key (6 byte optimization) 17",
    "category": "Documents / Archives"
  },
  {
    "mode": "25300",
    "name": "MS Office 2016 - SheetProtection",
    "category": "Documents / Archives"
  },
  {
    "mode": "25400",
    "name": "PDF 1.4 - 1.6 (Acrobat 5 - 8) - user and owner pass",
    "category": "Documents / Archives"
  },
  {
    "mode": "32300",
    "name": "Empire CMS (Admin password)",
    "category": "Documents / Archives"
  },
  {
    "mode": "6231",
    "name": "TrueCrypt 5.0+ Whirlpool + AES (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "6232",
    "name": "TrueCrypt 5.0+ Whirlpool + AES-Twofish (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "6233",
    "name": "TrueCrypt 5.0+ Whirlpool + AES-Twofish-Serpent (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "13771",
    "name": "VeraCrypt Streebog-512 + XTS 512 bit (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "13772",
    "name": "VeraCrypt Streebog-512 + XTS 1024 bit (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "13773",
    "name": "VeraCrypt Streebog-512 + XTS 1536 bit (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "13781",
    "name": "VeraCrypt Streebog-512 + XTS 512 bit + boot-mode (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "13782",
    "name": "VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "13783",
    "name": "VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode (legacy)",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "14600",
    "name": "LUKS v1 (legacy) 10",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "16700",
    "name": "FileVault 2",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "22100",
    "name": "BitLocker",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29311",
    "name": "TrueCrypt RIPEMD160 + XTS 512 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29312",
    "name": "TrueCrypt RIPEMD160 + XTS 1024 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29313",
    "name": "TrueCrypt RIPEMD160 + XTS 1536 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29331",
    "name": "TrueCrypt Whirlpool + XTS 512 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29332",
    "name": "TrueCrypt Whirlpool + XTS 1024 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29333",
    "name": "TrueCrypt Whirlpool + XTS 1536 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29341",
    "name": "TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29342",
    "name": "TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29343",
    "name": "TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29411",
    "name": "VeraCrypt RIPEMD160 + XTS 512 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29412",
    "name": "VeraCrypt RIPEMD160 + XTS 1024 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29413",
    "name": "VeraCrypt RIPEMD160 + XTS 1536 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29431",
    "name": "VeraCrypt Whirlpool + XTS 512 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29432",
    "name": "VeraCrypt Whirlpool + XTS 1024 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29433",
    "name": "VeraCrypt Whirlpool + XTS 1536 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29441",
    "name": "VeraCrypt RIPEMD160 + XTS 512 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29442",
    "name": "VeraCrypt RIPEMD160 + XTS 1024 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29443",
    "name": "VeraCrypt RIPEMD160 + XTS 1536 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29471",
    "name": "VeraCrypt Streebog-512 + XTS 512 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29472",
    "name": "VeraCrypt Streebog-512 + XTS 1024 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29473",
    "name": "VeraCrypt Streebog-512 + XTS 1536 bit",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29481",
    "name": "VeraCrypt Streebog-512 + XTS 512 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29482",
    "name": "VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29483",
    "name": "VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29541",
    "name": "LUKS v1 RIPEMD-160 + AES",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29542",
    "name": "LUKS v1 RIPEMD-160 + Serpent",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "29543",
    "name": "LUKS v1 RIPEMD-160 + Twofish",
    "category": "Full-Disk Encryption"
  },
  {
    "mode": "11300",
    "name": "Bitcoin/Litecoin wallet.dat",
    "category": "Cryptocurrency"
  },
  {
    "mode": "12700",
    "name": "Blockchain, My Wallet",
    "category": "Cryptocurrency"
  },
  {
    "mode": "15200",
    "name": "Blockchain, My Wallet, V2",
    "category": "Cryptocurrency"
  },
  {
    "mode": "15700",
    "name": "Ethereum Wallet, SCRYPT",
    "category": "Cryptocurrency"
  },
  {
    "mode": "16600",
    "name": "Electrum Wallet (Salt-Type 1-3)",
    "category": "Cryptocurrency"
  },
  {
    "mode": "21700",
    "name": "Electrum Wallet (Salt-Type 4)",
    "category": "Cryptocurrency"
  },
  {
    "mode": "21800",
    "name": "Electrum Wallet (Salt-Type 5)",
    "category": "Cryptocurrency"
  },
  {
    "mode": "25500",
    "name": "Stargazer Stellar Wallet XLM",
    "category": "Cryptocurrency"
  },
  {
    "mode": "26600",
    "name": "MetaMask Wallet 8",
    "category": "Cryptocurrency"
  },
  {
    "mode": "26610",
    "name": "MetaMask Wallet (short hash, plaintext check) 8 *",
    "category": "Cryptocurrency"
  },
  {
    "mode": "27700",
    "name": "MultiBit Classic.wallet (scrypt)",
    "category": "Cryptocurrency"
  },
  {
    "mode": "28200",
    "name": "Exodus Desktop Wallet (scrypt)",
    "category": "Cryptocurrency"
  },
  {
    "mode": "28501",
    "name": "Bitcoin WIF private key (P2PKH), compressed 26",
    "category": "Cryptocurrency"
  },
  {
    "mode": "28502",
    "name": "Bitcoin WIF private key (P2PKH), uncompressed 27",
    "category": "Cryptocurrency"
  },
  {
    "mode": "28503",
    "name": "Bitcoin WIF private key (P2WPKH, Bech32), compressed 28",
    "category": "Cryptocurrency"
  },
  {
    "mode": "28504",
    "name": "Bitcoin WIF private key (P2WPKH, Bech32), uncompressed 29",
    "category": "Cryptocurrency"
  },
  {
    "mode": "28505",
    "name": "Bitcoin WIF private key (P2SH(P2WPKH)), compressed 30",
    "category": "Cryptocurrency"
  },
  {
    "mode": "28506",
    "name": "Bitcoin WIF private key (P2SH(P2WPKH)), uncompressed 31",
    "category": "Cryptocurrency"
  },
  {
    "mode": "29800",
    "name": "Bisq.wallet (scrypt) *",
    "category": "Cryptocurrency"
  },
  {
    "mode": "30901",
    "name": "Bitcoin raw private key (P2PKH), compressed 33 *",
    "category": "Cryptocurrency"
  },
  {
    "mode": "30902",
    "name": "Bitcoin raw private key (P2PKH), uncompressed 34 *",
    "category": "Cryptocurrency"
  },
  {
    "mode": "30903",
    "name": "Bitcoin raw private key (P2WPKH, Bech32), compressed 35 *",
    "category": "Cryptocurrency"
  },
  {
    "mode": "30904",
    "name": "Bitcoin raw private key (P2WPKH, Bech32), uncompressed 36 *",
    "category": "Cryptocurrency"
  },
  {
    "mode": "30905",
    "name": "Bitcoin raw private key (P2SH(P2WPKH)), compressed 37 *",
    "category": "Cryptocurrency"
  },
  {
    "mode": "30906",
    "name": "Bitcoin raw private key (P2SH(P2WPKH)), uncompressed 38 *",
    "category": "Cryptocurrency"
  },
  {
    "mode": "31900",
    "name": "MataMask Mobile Wallet",
    "category": "Cryptocurrency"
  },
  {
    "mode": "6800",
    "name": "LastPass + LastPass sniffed 4",
    "category": "Password Managers"
  },
  {
    "mode": "13400",
    "name": "KeePass 1 AES / without keyfile",
    "category": "Password Managers"
  },
  {
    "mode": "23400",
    "name": "Bitwarden",
    "category": "Password Managers"
  },
  {
    "mode": "29700",
    "name": "KeePass 1 (AES/Twofish) and KeePass 2 (AES) - keyfile only mode 32",
    "category": "Password Managers"
  },
  {
    "mode": "22",
    "name": "Juniper NetScreen/SSG (ScreenOS)",
    "category": "Network Protocols"
  },
  {
    "mode": "111",
    "name": "nsldaps, SSHA-1(Base64), Netscape LDAP SSHA",
    "category": "Network Protocols"
  },
  {
    "mode": "501",
    "name": "Juniper IVE",
    "category": "Network Protocols"
  },
  {
    "mode": "1411",
    "name": "SSHA-256(Base64), LDAP {SSHA256}",
    "category": "Network Protocols"
  },
  {
    "mode": "1711",
    "name": "SSHA-512(Base64), LDAP {SSHA512}",
    "category": "Network Protocols"
  },
  {
    "mode": "9300",
    "name": "Cisco-IOS $9$ (scrypt)",
    "category": "Network Protocols"
  },
  {
    "mode": "15100",
    "name": "Juniper/NetBSD sha1crypt",
    "category": "Network Protocols"
  },
  {
    "mode": "21",
    "name": "osCommerce, xt:Commerce",
    "category": "Other"
  },
  {
    "mode": "23",
    "name": "Skype",
    "category": "Other"
  },
  {
    "mode": "24",
    "name": "SolarWinds Serv-U",
    "category": "Other"
  },
  {
    "mode": "125",
    "name": "ArubaOS",
    "category": "Other"
  },
  {
    "mode": "133",
    "name": "PeopleSoft",
    "category": "Other"
  },
  {
    "mode": "141",
    "name": "Episerver 6.x <.NET 4",
    "category": "Other"
  },
  {
    "mode": "900",
    "name": "MD4",
    "category": "Other"
  },
  {
    "mode": "1100",
    "name": "Domain Cached Credentials (DCC), MS Cache",
    "category": "Other"
  },
  {
    "mode": "1421",
    "name": "hMailServer",
    "category": "Other"
  },
  {
    "mode": "1441",
    "name": "Episerver 6.x >=.NET 4",
    "category": "Other"
  },
  {
    "mode": "2000",
    "name": "STDOUT",
    "category": "Other"
  },
  {
    "mode": "2612",
    "name": "PHPS",
    "category": "Other"
  },
  {
    "mode": "4521",
    "name": "Redmine",
    "category": "Other"
  },
  {
    "mode": "6000",
    "name": "RIPEMD-160",
    "category": "Other"
  },
  {
    "mode": "6100",
    "name": "Whirlpool",
    "category": "Other"
  },
  {
    "mode": "6300",
    "name": "AIX {smd5}",
    "category": "Other"
  },
  {
    "mode": "6400",
    "name": "AIX {ssha256}",
    "category": "Other"
  },
  {
    "mode": "6500",
    "name": "AIX {ssha512}",
    "category": "Other"
  },
  {
    "mode": "6700",
    "name": "AIX {ssha1}",
    "category": "Other"
  },
  {
    "mode": "6900",
    "name": "GOST R 34.11-94",
    "category": "Other"
  },
  {
    "mode": "7000",
    "name": "FortiGate (FortiOS)",
    "category": "Other"
  },
  {
    "mode": "7200",
    "name": "GRUB 2",
    "category": "Other"
  },
  {
    "mode": "7700",
    "name": "SAP CODVN B (BCODE)",
    "category": "Other"
  },
  {
    "mode": "7701",
    "name": "SAP CODVN B (BCODE) from RFC \\_READ\\_TABLE",
    "category": "Other"
  },
  {
    "mode": "7800",
    "name": "SAP CODVN F/G (PASSCODE)",
    "category": "Other"
  },
  {
    "mode": "7801",
    "name": "SAP CODVN F/G (PASSCODE) from RFC \\_READ\\_TABLE",
    "category": "Other"
  },
  {
    "mode": "8300",
    "name": "DNSSEC (NSEC3)",
    "category": "Other"
  },
  {
    "mode": "8400",
    "name": "WBB3 (Woltlab Burning Board)",
    "category": "Other"
  },
  {
    "mode": "8500",
    "name": "RACF",
    "category": "Other"
  },
  {
    "mode": "8501",
    "name": "AS/400 DES",
    "category": "Other"
  },
  {
    "mode": "8600",
    "name": "Lotus Notes/Domino 5",
    "category": "Other"
  },
  {
    "mode": "8700",
    "name": "Lotus Notes/Domino 6",
    "category": "Other"
  },
  {
    "mode": "8800",
    "name": "Android FDE <= 4.3",
    "category": "Other"
  },
  {
    "mode": "8900",
    "name": "scrypt",
    "category": "Other"
  },
  {
    "mode": "9100",
    "name": "Lotus Notes/Domino 8",
    "category": "Other"
  },
  {
    "mode": "9900",
    "name": "Radmin2",
    "category": "Other"
  },
  {
    "mode": "10100",
    "name": "SipHash",
    "category": "Other"
  },
  {
    "mode": "10300",
    "name": "SAP CODVN H (PWDSALTEDHASH) iSSHA-1",
    "category": "Other"
  },
  {
    "mode": "11000",
    "name": "PrestaShop",
    "category": "Other"
  },
  {
    "mode": "11500",
    "name": "CRC32 5",
    "category": "Other"
  },
  {
    "mode": "11700",
    "name": "GOST R 34.11-2012 (Streebog) 256-bit, big-endian",
    "category": "Other"
  },
  {
    "mode": "11800",
    "name": "GOST R 34.11-2012 (Streebog) 512-bit, big-endian",
    "category": "Other"
  },
  {
    "mode": "12200",
    "name": "eCryptfs",
    "category": "Other"
  },
  {
    "mode": "12500",
    "name": "RAR3-hp",
    "category": "Other"
  },
  {
    "mode": "12600",
    "name": "ColdFusion 10+",
    "category": "Other"
  },
  {
    "mode": "12900",
    "name": "Android FDE (Samsung DEK)",
    "category": "Other"
  },
  {
    "mode": "13000",
    "name": "RAR5",
    "category": "Other"
  },
  {
    "mode": "13200",
    "name": "AxCrypt 1",
    "category": "Other"
  },
  {
    "mode": "13500",
    "name": "PeopleSoft PS\\_TOKEN",
    "category": "Other"
  },
  {
    "mode": "13900",
    "name": "OpenCart",
    "category": "Other"
  },
  {
    "mode": "14000",
    "name": "DES (PT = $salt, key = $pass) 8",
    "category": "Other"
  },
  {
    "mode": "14100",
    "name": "3DES (PT = $salt, key = $pass) 9",
    "category": "Other"
  },
  {
    "mode": "14200",
    "name": "RACF KDFAES",
    "category": "Other"
  },
  {
    "mode": "14500",
    "name": "Linux Kernel Crypto API (2.4)",
    "category": "Other"
  },
  {
    "mode": "14700",
    "name": "iTunes backup 11",
    "category": "Other"
  },
  {
    "mode": "14800",
    "name": "iTunes backup >= 10.0 11",
    "category": "Other"
  },
  {
    "mode": "14900",
    "name": "Skip32 (PT = $salt, key = $pass) 12",
    "category": "Other"
  },
  {
    "mode": "15000",
    "name": "FileZilla Server >= 0.9.55",
    "category": "Other"
  },
  {
    "mode": "15300",
    "name": "DPAPI masterkey file v1 + local context",
    "category": "Other"
  },
  {
    "mode": "15310",
    "name": "DPAPI masterkey file v1 (context 3) *",
    "category": "Other"
  },
  {
    "mode": "15400",
    "name": "ChaCha20 20",
    "category": "Other"
  },
  {
    "mode": "15910",
    "name": "DPAPI masterkey file v2 (context 3)",
    "category": "Other"
  },
  {
    "mode": "16000",
    "name": "Tripcode",
    "category": "Other"
  },
  {
    "mode": "16100",
    "name": "TACACS+",
    "category": "Other"
  },
  {
    "mode": "16500",
    "name": "JWT (JSON Web Token)",
    "category": "Other"
  },
  {
    "mode": "16900",
    "name": "Ansible Vault",
    "category": "Other"
  },
  {
    "mode": "18700",
    "name": "Java Object hashCode()",
    "category": "Other"
  },
  {
    "mode": "18900",
    "name": "Android Backup",
    "category": "Other"
  },
  {
    "mode": "21500",
    "name": "SolarWinds Orion",
    "category": "Other"
  },
  {
    "mode": "21501",
    "name": "SolarWinds Orion v2",
    "category": "Other"
  },
  {
    "mode": "22700",
    "name": "MultiBit HD (scrypt)",
    "category": "Other"
  },
  {
    "mode": "22911",
    "name": "RSA/DSA/EC/OpenSSH Private Keys ($0$)",
    "category": "Other"
  },
  {
    "mode": "22921",
    "name": "RSA/DSA/EC/OpenSSH Private Keys ($6$)",
    "category": "Other"
  },
  {
    "mode": "22931",
    "name": "RSA/DSA/EC/OpenSSH Private Keys ($1, $3$)",
    "category": "Other"
  },
  {
    "mode": "22941",
    "name": "RSA/DSA/EC/OpenSSH Private Keys ($4$)",
    "category": "Other"
  },
  {
    "mode": "22951",
    "name": "RSA/DSA/EC/OpenSSH Private Keys ($5$)",
    "category": "Other"
  },
  {
    "mode": "23001",
    "name": "SecureZIP AES-128",
    "category": "Other"
  },
  {
    "mode": "23002",
    "name": "SecureZIP AES-192",
    "category": "Other"
  },
  {
    "mode": "23003",
    "name": "SecureZIP AES-256",
    "category": "Other"
  },
  {
    "mode": "23500",
    "name": "AxCrypt 2 AES-128",
    "category": "Other"
  },
  {
    "mode": "23600",
    "name": "AxCrypt 2 AES-256",
    "category": "Other"
  },
  {
    "mode": "23700",
    "name": "RAR3-p (Uncompressed)",
    "category": "Other"
  },
  {
    "mode": "23800",
    "name": "RAR3-p (Compressed)",
    "category": "Other"
  },
  {
    "mode": "23900",
    "name": "BestCrypt v3 Volume Encryption",
    "category": "Other"
  },
  {
    "mode": "24000",
    "name": "BestCrypt v4 Volume Encryption",
    "category": "Other"
  },
  {
    "mode": "24600",
    "name": "SQLCipher",
    "category": "Other"
  },
  {
    "mode": "24700",
    "name": "Stuffit5",
    "category": "Other"
  },
  {
    "mode": "25700",
    "name": "MurmurHash",
    "category": "Other"
  },
  {
    "mode": "25900",
    "name": "KNX IP Secure - Device Authentication Code",
    "category": "Other"
  },
  {
    "mode": "26000",
    "name": "Mozilla key3.db",
    "category": "Other"
  },
  {
    "mode": "26100",
    "name": "Mozilla key4.db",
    "category": "Other"
  },
  {
    "mode": "26200",
    "name": "OpenEdge Progress Encode",
    "category": "Other"
  },
  {
    "mode": "26300",
    "name": "FortiGate256 (FortiOS256)",
    "category": "Other"
  },
  {
    "mode": "26401",
    "name": "AES-128-ECB NOKDF (PT = $salt, key = $pass)",
    "category": "Other"
  },
  {
    "mode": "26402",
    "name": "AES-192-ECB NOKDF (PT = $salt, key = $pass)",
    "category": "Other"
  },
  {
    "mode": "26403",
    "name": "AES-256-ECB NOKDF (PT = $salt, key = $pass)",
    "category": "Other"
  },
  {
    "mode": "26500",
    "name": "iPhone passcode (UID key + System Keybag)",
    "category": "Other"
  },
  {
    "mode": "27800",
    "name": "MurmurHash3",
    "category": "Other"
  },
  {
    "mode": "27900",
    "name": "CRC32C",
    "category": "Other"
  },
  {
    "mode": "28000",
    "name": "CRC64Jones",
    "category": "Other"
  },
  {
    "mode": "28300",
    "name": "Teamspeak 3 (channel hash)",
    "category": "Other"
  },
  {
    "mode": "29200",
    "name": "Radmin3",
    "category": "Other"
  },
  {
    "mode": "30700",
    "name": "Anope IRC Services (enc\\_sha256) *",
    "category": "Other"
  },
  {
    "mode": "31100",
    "name": "SM3 *",
    "category": "Other"
  },
  {
    "mode": "31200",
    "name": "Veeam VBK *",
    "category": "Other"
  },
  {
    "mode": "31300",
    "name": "MS SNTP *",
    "category": "Other"
  },
  {
    "mode": "31400",
    "name": "SecureCRT MasterPassphrase v2",
    "category": "Other"
  },
  {
    "mode": "32600",
    "name": "CubeCart (whirlpool($salt.$pass.$salt))",
    "category": "Other"
  },
  {
    "mode": "32700",
    "name": "Kremlin Encrypt 3.0 w/NewDES",
    "category": "Other"
  },
  {
    "mode": "33600",
    "name": "RIPEMD-320",
    "category": "Other"
  },
  {
    "mode": "34000",
    "name": "Argon2",
    "category": "Other"
  },
  {
    "mode": "34200",
    "name": "MurmurHash64A",
    "category": "Other"
  },
  {
    "mode": "34201",
    "name": "MurmurHash64A (zero seed)",
    "category": "Other"
  },
  {
    "mode": "34211",
    "name": "MurmurHash64A truncated (zero seed)",
    "category": "Other"
  },
  {
    "mode": "34600",
    "name": "MD6 (256)",
    "category": "Other"
  },
  {
    "mode": "35000",
    "name": "SAP CODVN H (PWDSALTEDHASH) isSHA512",
    "category": "Other"
  },
  {
    "mode": "35200",
    "name": "AS/400 SSHA1",
    "category": "Other"
  },
  {
    "mode": "70000",
    "name": "Argon2id \\[Bridged: reference implementation + tunings\\]",
    "category": "Other"
  },
  {
    "mode": "70100",
    "name": "scrypt \\[Bridged: Scrypt-Jane SMix\\]",
    "category": "Other"
  },
  {
    "mode": "70200",
    "name": "scrypt \\[Bridged: Scrypt-Yescrypt\\]",
    "category": "Other"
  },
  {
    "mode": "72000",
    "name": "Generic Hash \\[Bridged: Python Interpreter free-threading\\]",
    "category": "Other"
  },
  {
    "mode": "73000",
    "name": "Generic Hash \\[Bridged: Python Interpreter with GIL\\]",
    "category": "Other"
  },
  {
    "mode": "74000",
    "name": "Generic Hash \\[Bridged: Rust\\]",
    "category": "Other"
  },
  {
    "mode": "99999",
    "name": "Plaintext",
    "category": "Other"
  }
];

/** Look up a HashType by mode number string */
export function getHashTypeByMode(mode: string): HashType | undefined {
  return HASH_TYPES.find(h => h.mode === mode);
}

/** Group HASH_TYPES by category, preserving HASH_TYPE_CATEGORIES order */
export function getHashTypesByCategory(): Map<string, HashType[]> {
  const map = new Map<string, HashType[]>();
  for (const cat of HASH_TYPE_CATEGORIES) {
    const items = HASH_TYPES.filter(h => h.category === cat);
    if (items.length > 0) map.set(cat, items);
  }
  return map;
}
